### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by CubeMD** [mbaske/ml-dogfight#1]
Hey,
Nice job with the project, however ml-agents are missing from the project.
Steps to replicate:
Download project
Launch with Unity
Assets\Dogfight\Scripts\BasicAgent.cs(2,7): error CS0246: The type or namespace name 'MLAgents' could not be found (are you missing a using directive or an assembly reference?)

**Comment by mbaske** [comment]
Thanks! Yeah, I didn't want to duplicate the ml-agents files in this repo. Please get the [targeted release](https://github.com/Unity-Technologies/ml-agents/releases/tag/0.12.0) and copy the files from the [Assets folder](https://github.com/Unity-Technologies/ml-agents/tree/master/UnitySDK/Assets).
